version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{s3_bucket_url}}"
        BUILD_FOLDER: "dist"
phases:
  install:
    commands:
        - echo Installing source NPM dependencies...
        - cd littleFriends
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started
        - ls
        - ng build
artifacts:
    files:
        - 'littleFriends/**/*'
    base-directory: 'dist*'
    discard-paths: yes
