version: 0.2

env:
    variables:
        BUILD_FOLDER: "dist"
phases:
  install:
    commands:
        - echo Installing source NPM dependencies...
        - cd littleFriends
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started
        - ls
        - ng build --prod
post_build:
    commands:
      - aws s3 cp ./littlefriends/dist/little-friends s3://elasticbeanstalk-us-east-2-372011782528 --recursive
      - aws elasticbeanstalk create-application-version --application-name proyecto-software --version-label 1.04 --source-bundle S3Bucket="elasticbeanstalk-us-east-2-372011782528"

artifacts:
    files:
        - '**/*'
    base-directory: 'littleFriends/dist*'
    discard-paths: yes
